### ISSUE TITLE
Missing jbox2d dependencies

### ISSUE THREAD

**Issue by maplebar** [davidholiday/ALTk#16]
Won't build, the local maven repo just has the .pom files and does not include the .jar's for the jbox2d dependencies.

`[ERROR] Failed to execute goal on project altK: Could not resolve dependencies for project altK:altK:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.jbox2d:jbox2d-testbed:jar:2.3.1-SNAPSHOT, org.jbox2d:jbox2d-library:jar:2.3.1-SNAPSHOT, org.jbox2d:jbox2d-serialization:jar:2.3.1-SNAPSHOT: Could not find artifact org.jbox2d:jbox2d-testbed:jar:2.3.1-SNAPSHOT in local-repo (file:///home/jmapes/wk/ALTk/altk/lib) -> [Help 1]`

**Comment by davidholiday** [comment]
hmm -- looks like the jar files didn't get uploaded. let me check the gitignore file

**Comment by davidholiday** [comment]
yarp that was it. should be gtg now

**Comment by maplebar** [comment]
It builds for me now.
